# Thai translation for linuxmint
# Copyright (c) 2009 Rosetta Contributors and Canonical Ltd 2009
# This file is distributed under the same license as the linuxmint package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2009.
#
msgid ""
msgstr ""
"Project-Id-Version: linuxmint\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2016-11-02 13:58+0000\n"
"PO-Revision-Date: 2017-03-26 15:45+0000\n"
"Last-Translator: Rockworld <sumoisrock@gmail.com>\n"
"Language-Team: Thai <th@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2017-05-06 12:34+0000\n"
"X-Generator: Launchpad (build 18366)\n"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:111
#: usr/lib/linuxmint/mintbackup/mintbackup.py:251
#: usr/lib/linuxmint/mintbackup/mintbackup.py:443
#: usr/lib/linuxmint/mintbackup/mintbackup.py:461
#: usr/lib/linuxmint/mintbackup/mintbackup.py:527
#: usr/lib/linuxmint/mintbackup/mintbackup.py:530
#: usr/lib/linuxmint/mintbackup/mintbackup.py:582
#: usr/lib/linuxmint/mintbackup/mintbackup.py:585
#: usr/lib/linuxmint/mintbackup/mintbackup.py:605
#: usr/lib/linuxmint/mintbackup/mintbackup.py:628
#: usr/lib/linuxmint/mintbackup/mintbackup.py:635
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1499
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1597
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1605
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1661 generate_desktop_files.py:26
#: generate_desktop_files.py:41
msgid "Backup Tool"
msgstr "เครื่องมือสำรองข้อมูล"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:168
msgid "Preserve structure"
msgstr "รักษาโครงสร้างไว้ด้วย"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:170
msgid ".tar file"
msgstr "แฟ้ม .tar"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:171
msgid ".tar.bz2 file"
msgstr "แฟ้ม .tar.bz2"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:172
msgid ".tar.gz file"
msgstr "แฟ้ม .tar.gz"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:178
msgid "Never"
msgstr "ไม่เลย"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:179
msgid "Size mismatch"
msgstr "ขนาดไม่ตรงกัน"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:180
msgid "Modification time mismatch"
msgstr "เวลาแก้ไขไม่ตรงกัน"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:181
msgid "Checksum mismatch"
msgstr "การตรวจสอบไม่ตรงกัน"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:182
msgid "Always"
msgstr "เสมอ"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:204
msgid "Excluded paths"
msgstr "เส้นทางที่ยกเว้นไว้"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:214
msgid "Type"
msgstr "ประเภท"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:218
msgid "Detail"
msgstr "รายละเอียด"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:224
#: usr/lib/linuxmint/mintbackup/mintbackup.py:233
msgid "Path"
msgstr "เส้นทาง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:227
#: usr/lib/linuxmint/mintbackup/mintbackup.py:236
msgid "Error"
msgstr "ผิดพลาด"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:268
msgid "Store?"
msgstr "ต้องการเก็บไว้หรือไม่?"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:271
#: usr/lib/linuxmint/mintbackup/mintbackup.py:284
msgid "Name"
msgstr "ชื่อ"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:281
msgid "Install"
msgstr "ติดตั้ง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:289
msgid "Backup or Restore"
msgstr "กู้คืน"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:290
msgid "Choose from the following options"
msgstr "เลือกจากตัวเลือกดังต่อไปนี้"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:292
#: usr/lib/linuxmint/mintbackup/mintbackup.py:303
#: usr/lib/linuxmint/mintbackup/mintbackup.py:317
#: usr/lib/linuxmint/mintbackup/mintbackup.py:324
#: usr/lib/linuxmint/mintbackup/mintbackup.py:328
#: usr/lib/linuxmint/mintbackup/mintbackup.py:333
msgid "Backup files"
msgstr "สำรองแฟ้ม"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:293
#: usr/lib/linuxmint/mintbackup/mintbackup.py:337
#: usr/lib/linuxmint/mintbackup/mintbackup.py:347
#: usr/lib/linuxmint/mintbackup/mintbackup.py:353
#: usr/lib/linuxmint/mintbackup/mintbackup.py:358
msgid "Restore files"
msgstr "กู้คืนแฟ้ม"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:294
#: usr/lib/linuxmint/mintbackup/mintbackup.py:362
#: usr/lib/linuxmint/mintbackup/mintbackup.py:367
#: usr/lib/linuxmint/mintbackup/mintbackup.py:373
#: usr/lib/linuxmint/mintbackup/mintbackup.py:378
msgid "Backup software selection"
msgstr "สำรองข้อมูลการเลือกซอฟต์แวร์"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:295
#: usr/lib/linuxmint/mintbackup/mintbackup.py:382
#: usr/lib/linuxmint/mintbackup/mintbackup.py:387
#: usr/lib/linuxmint/mintbackup/mintbackup.py:394
msgid "Restore software selection"
msgstr "กู้คืนข้อมูลการเลือกซอฟต์แวร์"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:297
msgid "Make a backup of your files"
msgstr "ทำการสำรองแฟ้มต่าง ๆ ของคุณ"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:298
msgid "Save the list of installed applications"
msgstr "บันทึกรายการโปรแกรมที่ติดตั้งแล้ว"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:299
msgid "Restore a previous backup"
msgstr "กู้คืนข้อมูลสำรองก่อนหน้า"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:300
msgid "Restore previously installed applications"
msgstr "กู้คืนโปรแกรมที่ติดตั้งแล้วเมื่อก่อนหน้านี้"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:304
msgid "Please select a source and a destination for your backup"
msgstr "กรุณาเลือกต้นทางและปลายทางสำหรับการสำรองข้อมูลของคุณ"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:305
#: usr/lib/linuxmint/mintbackup/mintbackup.py:341
#: usr/lib/linuxmint/mintbackup/mintbackup.py:349
msgid "Source:"
msgstr "ต้นทาง:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:306
#: usr/lib/linuxmint/mintbackup/mintbackup.py:342
msgid "Destination:"
msgstr "ปลายทาง:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:307
#: usr/lib/linuxmint/mintbackup/mintbackup.py:343
msgid "Advanced options"
msgstr "ตัวเลือกขั้นสูง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:308
#: usr/lib/linuxmint/mintbackup/mintbackup.py:350
msgid "Description:"
msgstr "รายละเอียด:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:309
msgid "Output:"
msgstr "เอาต์พุต:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:310
#: usr/lib/linuxmint/mintbackup/mintbackup.py:344
msgid "Overwrite:"
msgstr "เขียนทับ:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:311
msgid "Confirm integrity"
msgstr "ยืนยันความสมบูรณ์"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:312
msgid "Follow symlinks"
msgstr "ตามการเชื่อมโยงไป"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:313
msgid "Preserve permissions"
msgstr "รักษาสิทธิ์ที่อนุญาตด้วย"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:314
msgid "Preserve timestamps"
msgstr "รักษาการบันทึกเวลาด้วย"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:318
msgid "Please select any files or directories you want to exclude"
msgstr "กรุณาเลือกแฟ้มหรือตำแหน่งใด ๆ ที่คุณต้องการยกเว้น"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:319
msgid "Exclude files"
msgstr "ทำการยกเว้นแฟ้ม"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:320
msgid "Exclude directories"
msgstr "ทำการยกเว้นตำแหน่ง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:321
msgid "Remove"
msgstr "เอาออก"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:325
msgid "Please review the information below before starting the backup"
msgstr "กรุณาเขียนข้อมูลข้างล่างก่อนเริ่มทำการสำรองข้อมูล"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:329
msgid "Please wait while your files are being backed up"
msgstr "กรุณารอขณะที่แฟ้มต่าง ๆ ของคุณกำลังถูกสำรองไว้"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:330
#: usr/lib/linuxmint/mintbackup/mintbackup.py:375
msgid "Backing up:"
msgstr "กำลังสำรองข้อมูล:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:334
#: usr/lib/linuxmint/mintbackup/mintbackup.py:379
msgid "The backup is now finished"
msgstr "สำรองข้อมูลเสร็จสิ้น"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:338
msgid ""
"Please choose the type of backup to restore, its location and a destination"
msgstr ""
"เลือกประเภทของข้อมูลสำรองที่จะกู้คืน "
"รวมทั้งตำแหน่งที่ตั้งและปลายทางของมันด้วย"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:339
msgid "Archive"
msgstr "แฟ้มจัดเก็บ"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:340
msgid "Directory"
msgstr "ตำแหน่ง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:348
msgid "Please review the information below"
msgstr "กรุณาเขียนข้อมูลข้างล่างด้วย"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:354
msgid "Please wait while your files are being restored"
msgstr "กรุณารอขณะที่แฟ้มต่าง ๆ ของคุณกำลังถูกกู้คืน"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:355
msgid "Restoring:"
msgstr "กำลังกู้คืน:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:359
msgid "The restoration of the files is now finished"
msgstr "การกู้คืนแฟ้มต่าง ๆ เสร็จสิ้น"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:363
msgid "Please choose a destination"
msgstr "กรุณาเลือกปลายทาง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:364
#: usr/lib/linuxmint/mintbackup/mintbackup.py:546
msgid "Destination"
msgstr "ปลายทาง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:368
msgid "The list below shows the packages you added to Linux Mint"
msgstr "รายการข้างล่างแสดงแพกเกจที่คุณได้เพิ่มเข้าไปในลินุกซ์มินต์"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:369
#: usr/lib/linuxmint/mintbackup/mintbackup.py:389
msgid "Select all"
msgstr "เลือกทั้งหมด"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:370
#: usr/lib/linuxmint/mintbackup/mintbackup.py:390
msgid "Deselect all"
msgstr "เลิกการเลือกทั้งหมด"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:374
msgid "Please wait while your software selection is being backed up"
msgstr "กรุณารอขณะที่การเลือกซอฟต์แวร์ของคุณกำลังถูกสำรอง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:383
msgid "Please select a saved software selection"
msgstr "กรุณาเลือกการเลือกซอฟต์แวร์ที่บันทึกไว้"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:384
msgid "Software selection:"
msgstr "การเลือกซอฟต์แวร์:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:388
msgid "Select the packages you want to install"
msgstr "เลือกแพกเกจที่คุณต้องการจะติดตั้ง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:391
msgid "Refresh"
msgstr "เรียกใหม่อีกครั้ง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:395
msgid "The restoration is now finished"
msgstr "การกู้คืนเสร็จแล้ว"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:396
msgid "Your package selection was restored successfully"
msgstr "การเลือกแพกเกจของคุณได้กลับคืนมาอย่างสมบูรณ์แล้ว"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:452
#: usr/lib/linuxmint/mintbackup/mintbackup.py:470
msgid "Invalid path"
msgstr "เส้นทางไม่ถูกต้อง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:452
#: usr/lib/linuxmint/mintbackup/mintbackup.py:470
#, python-format
msgid "%s is not located within your source directory. Not added."
msgstr "%s ไม่ได้ตั้งตำแหน่งภายในตำแหน่งต้นทางของคุณและจะไม่เพิ่มเข้า"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:527
msgid "Please choose directories for the source and the destination"
msgstr "กรุณาเลือกตำแหน่งของต้นทางและปลายทาง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:530
msgid ""
"Please choose different directories for the source and the destination"
msgstr "กรุณาเลือกตำแหน่งที่แตกต่างกันของต้นทางและปลายทาง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:545
msgid "Source"
msgstr "ต้นทาง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:548
msgid "Description"
msgstr "รายละเอียด"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:552
msgid "Compression"
msgstr "การบีบอัดข้อมูล"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:556
msgid "Overwrite destination files"
msgstr "เขียนทับแฟ้มปลายทาง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:559
msgid "Exclude"
msgstr "ไม่นับรวม"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:582
msgid "Please choose a file to restore from"
msgstr "กรุณาเลือกแฟ้มที่จะกู้คืน"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:585
#: usr/lib/linuxmint/mintbackup/mintbackup.py:605
msgid "Please choose a destination directory"
msgstr "กรุณาเลือกตำแหน่งปลายทาง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:628
msgid "No packages need to be installed at this time"
msgstr "ไม่มีแพกเกจที่จะต้องติดตั้งในเวลานี้"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:635
msgid "Please select one or more packages to install"
msgstr "กรุณาเลือกหนึ่งแพกเกจหรือมากกว่านั้นที่จะติดตั้ง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:703
#: usr/lib/linuxmint/mintbackup/mintbackup.py:704
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1206
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1208
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1514
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1515
msgid "Calculating..."
msgstr "กำลังคำนวณ..."

#: usr/lib/linuxmint/mintbackup/mintbackup.py:719
#, python-format
msgid "Skipping %(skipped_file)s because named pipes are not supported."
msgstr "กำลังข้าม %(skipped_file)s เนื่องจากไม่สนับสนุนเนมไปป์"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:761
#: usr/lib/linuxmint/mintbackup/mintbackup.py:801
msgid "Skipping broken link"
msgstr "ข้ามลิงก์ที่ชำรุด"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:762
msgid "Broken link"
msgstr "ลิงก์ที่ชำรุด"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:765
#: usr/lib/linuxmint/mintbackup/mintbackup.py:805
msgid "Skipping link"
msgstr "ข้ามลิงก์"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:829
#: usr/lib/linuxmint/mintbackup/mintbackup.py:838
#: usr/lib/linuxmint/mintbackup/mintbackup.py:847
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1267
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1278
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1291
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1355
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1364
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1374
msgid "Skipping identical file"
msgstr "ข้ามแฟ้มที่เหมือนกัน"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:869
#, python-format
msgid ""
"Warning: Some files were not saved, copied: %(current_file)d files out of "
"%(total)d total"
msgstr ""
"คำเตือน: บางแฟ้มอาจไม่ถูกบันทึก คัดลอกแล้ว %(current_file)d แฟ้มจาก "
"%(total)d แฟ้มทั้งหมด"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:873
msgid "An error occurred during the backup"
msgstr "เกิดข้อผิดพลาดระหว่างการสำรองข้อมูล"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:883
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1560
msgid "The backup was aborted"
msgstr "การสำรองข้อมูลถูกยกเลิก"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:891
msgid "The backup completed successfully"
msgstr "การสำรองข้อมูลเสร็จสิ้น"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:982
msgid "Checksum Mismatch:"
msgstr "การตรวจสอบไม่ตรงกัน:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:983
msgid "Checksum Mismatch"
msgstr "การตรวจสอบไม่ตรงกัน"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1035
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1037
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1066
msgid "Calculating checksum"
msgstr "กำลังคำนวณการตรวจสอบ"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1112
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1136
msgid "(Not created with the Backup Tool)"
msgstr "(ไม่ได้สร้างจากเครื่องมือสำรองข้อมูล)"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1398
#, python-format
msgid ""
"Warning: Some files were not restored, copied: %(current_file)d files out of "
"%(total)d total"
msgstr ""
"คำเตือน: บางแฟ้มอาจไม่ถูกกู้คืน คัดลอกแล้ว %(current_file)d แฟ้มจาก "
"%(total)d แฟ้มทั้งหมด"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1401
msgid "An error occurred during the restoration"
msgstr "เกิดข้อผิดพลาดระหว่างการกู้คืนข้อมูล"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1412
msgid "The restoration was aborted"
msgstr "การกู้คืนถูกยกเลิก"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1420
msgid "The restoration completed successfully"
msgstr "การกู้คืนเสร็จสิ้น"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1551
msgid "An error occurred during the backup:"
msgstr "เกิดข้อผิดพลาดระหว่างการสำรองข้อมูล:"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1568
msgid "Your software selection was backed up successfully"
msgstr "การเลือกซอฟต์แวร์ของคุณถูกสำรองข้อมูลไว้เรียบร้อยแล้ว"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1597
msgid "The specified file is not a valid software selection"
msgstr "แฟ้มที่ระบุไว้ไม่ใช่แฟ้มการเลือกซอฟต์แวร์ที่ถูกต้อง"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1605
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1661
msgid "An error occurred while accessing the file"
msgstr "มีปัญหาเกิดขึ้นขณะเข้าถึงแฟ้ม"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1648
#: usr/lib/linuxmint/mintbackup/mintbackup.py:1654
msgid "Could not locate the package"
msgstr "ไม่สามารถตั้งตำแหน่งแพกเกจ"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1686
msgid "Please wait, this can take some time"
msgstr "กรุณารอสักครู่ อาจจะใช้เวลาพอสมควร"

#: usr/lib/linuxmint/mintbackup/mintbackup.py:1688
msgid "The installation is complete"
msgstr "การติดตั้งสำเร็จ"

#: generate_desktop_files.py:26 generate_desktop_files.py:41
msgid "Make a backup of your home directory"
msgstr "สำรองข้อมูลในตำแหน่งของคุณ"

#~ msgid "Copying the backup file into your home directory..."
#~ msgstr "คัดลอกไฟล์สำรองข้อมูลไปยัง Directory ของคุณ"

#~ msgid "Cleaning up..."
#~ msgstr "กำลังปรับระบบให้เรียบร้อย..."

#~ msgid "Backup"
#~ msgstr "สำรองข้อมูล"

#~ msgid "Restore"
#~ msgstr "เรียกคืน"
